name: mobile_dev
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  flutter_tts: ^3.8.5
  latlong2: ^0.9.1
  http: ^1.2.2
  geolocator: ^9.0.2
  dart_frog: ^1.0.0
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/health-insurance.png
    - assets/mastercard_logo.png
